// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StudentEmail = "esermjila07@gmail.com",
                            StudentName = "Esethu Mjila",
                            StudentPhone = "0604269728"
                        },
                        new
                        {
                            StudentId = 2,
                            StudentEmail = "asivemyeni@gmail.com",
                            StudentName = "Asive Myeni",
                            StudentPhone = "0736379802"
                        },
                        new
                        {
                            StudentId = 3,
                            StudentEmail = "michael.j@example.com",
                            StudentName = "Michael Johnson",
                            StudentPhone = "555-111-2222"
                        },
                        new
                        {
                            StudentId = 4,
                            StudentEmail = "emily.d@example.com",
                            StudentName = "Emily Davis",
                            StudentPhone = "444-222-3333"
                        },
                        new
                        {
                            StudentId = 5,
                            StudentEmail = "william.b@example.com",
                            StudentName = "William Brown",
                            StudentPhone = "333-999-8888"
                        },
                        new
                        {
                            StudentId = 6,
                            StudentEmail = "jessica.t@example.com",
                            StudentName = "Jessica Taylor",
                            StudentPhone = "666-777-8888"
                        },
                        new
                        {
                            StudentId = 7,
                            StudentEmail = "david.w@example.com",
                            StudentName = "David Wilson",
                            StudentPhone = "777-888-9999"
                        },
                        new
                        {
                            StudentId = 8,
                            StudentEmail = "sarah.l@example.com",
                            StudentName = "Sarah Lee",
                            StudentPhone = "222-333-4444"
                        },
                        new
                        {
                            StudentId = 9,
                            StudentEmail = "james.w@example.com",
                            StudentName = "James White",
                            StudentPhone = "888-999-0000"
                        },
                        new
                        {
                            StudentId = 10,
                            StudentEmail = "ashley.h@example.com",
                            StudentName = "Ashley Harris",
                            StudentPhone = "999-000-1111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
